// Spec 011 T9.1: per-shard determinism under concurrent load.
//
// Runs an existing golden scenario (tests/replay/) on one shard while a DIFFERENT scenario runs
// CONCURRENTLY on a second, fully independent shard, then serializes the first shard's trades
// with the exact same text format tests/replay/replay_test.cpp uses and asserts byte-identical
// equality against the COMMITTED golden file. A shard whose output depends on its neighbour --
// through any accidentally-shared state -- fails here immediately, because the golden file was
// generated by the single-shard engine with no neighbour running at all.

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <sstream>
#include <thread>

#include "common/scenario.hpp"
#include "tests/shard/shard_test_helpers.hpp"

using namespace velox;
using namespace velox::shardtest;

namespace {

namespace fs = std::filesystem;

std::vector<common::ScenarioCommand> loadScenario(const std::string& name) {
    const fs::path p = fs::path(VELOX_REPLAY_DIR) / "scenarios" / (name + ".txt");
    std::ifstream in(p);
    EXPECT_TRUE(in.good()) << "cannot open scenario: " << p;
    return common::loadScenarioStream(in);
}

std::string loadGolden(const std::string& name) {
    const fs::path p = fs::path(VELOX_REPLAY_DIR) / "golden" / (name + ".golden");
    std::ifstream gf(p);
    EXPECT_TRUE(gf.good()) << "missing golden file: " << p;
    std::stringstream ss;
    ss << gf.rdbuf();
    return ss.str();
}

}  // namespace

TEST(ShardDeterminism, MeasuredShardIgnoresConcurrentNeighbour) {
    const std::string measuredScenario = "crossing_book";
    const std::string neighbourScenario = "cancel_replace";

    const auto measuredCmds = loadScenario(measuredScenario);
    const auto neighbourCmds = loadScenario(neighbourScenario);
    const std::string expected = loadGolden(measuredScenario);

    runtime::Shard measured(/*instrumentId=*/1, replayCompatibleConfig(),
                            makeShardTestDir("determinism_measured"), /*cpu=*/0);
    runtime::Shard neighbour(/*instrumentId=*/2, replayCompatibleConfig(),
                             makeShardTestDir("determinism_neighbour"), /*cpu=*/1);
    measured.recoverAndStart();
    neighbour.recoverAndStart();

    std::string measuredOutput;
    std::thread measuredThread(
        [&] { measuredOutput = driveScenarioThroughShard(measured, measuredCmds); });
    std::thread neighbourThread([&] { driveScenarioThroughShard(neighbour, neighbourCmds); });

    measuredThread.join();
    neighbourThread.join();

    EXPECT_EQ(measuredOutput, expected)
        << "shard output diverged from the single-shard golden while a neighbour shard ran "
           "concurrently -- something is shared across shards that should not be";

    measured.stop();
    neighbour.stop();
}

// Same shard, same scenario, run twice with no neighbour at all -- the direct sanity check that
// this harness reproduces the exact golden format runtime::Shard is supposed to preserve.
TEST(ShardDeterminism, SingleShardMatchesGoldenWithNoNeighbour) {
    const auto cmds = loadScenario("partial_fill");
    const std::string expected = loadGolden("partial_fill");

    runtime::Shard shard(/*instrumentId=*/7, replayCompatibleConfig(),
                         makeShardTestDir("determinism_solo"), /*cpu=*/0);
    shard.recoverAndStart();
    const std::string produced = driveScenarioThroughShard(shard, cmds);
    shard.stop();

    EXPECT_EQ(produced, expected);
}
